services:
  postgres:
    image: postgres:16
    container_name: task_management_postgres
    environment:
      POSTGRES_DB: task_management_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - task_management_data:/var/lib/postgresql/data

volumes:
  task_management_data:
